#!/bin/sh
set -eu

# Applies Voidline's generated palette to regular desktop applications. GTK
# loads gtk.css only when an application starts, while the standard GNOME
# appearance keys and Settings portal notify already-running applications that
# support live color-scheme changes.

valid_color() {
    printf '%s\n' "$1" | grep -Eq '^#[0-9A-Fa-f]{6}$'
}

valid_name() {
    case "$1" in
        ""|*[!A-Za-z0-9\ ._+-]*) return 1 ;;
        *) return 0 ;;
    esac
}

ensure_import() {
    css_file=$1
    directory=$(dirname "$css_file")
    mkdir -p "$directory"
    import='@import url("voidline.css");'

    if [ ! -f "$css_file" ]; then
        printf '%s\n' "$import" >"$css_file"
        return
    fi
    grep -Fqx "$import" "$css_file" && return

    temporary=$(mktemp "$directory/.gtk-css.XXXXXX")
    {
        printf '%s\n\n' "$import"
        cat "$css_file"
    } >"$temporary"
    chmod --reference="$css_file" "$temporary" 2>/dev/null || chmod 600 "$temporary"
    mv -f "$temporary" "$css_file"
}

update_settings_ini() {
    ini_file=$1
    ini_theme=$2
    ini_dark=$3
    ini_font=$4
    ini_icons=$5
    ini_cursor=$6
    directory=$(dirname "$ini_file")
    mkdir -p "$directory"
    temporary=$(mktemp "$directory/.gtk-settings.XXXXXX")

    if [ -f "$ini_file" ]; then
        source_file=$ini_file
    else
        source_file=/dev/null
    fi

    awk \
        -v theme="$ini_theme" \
        -v dark="$ini_dark" \
        -v font="$ini_font 11" \
        -v icons="$ini_icons" \
        -v cursor="$ini_cursor" '
        function emit_missing() {
            if (!seen_theme) print "gtk-theme-name=" theme
            if (!seen_dark && dark != "omit")
                print "gtk-application-prefer-dark-theme=" dark
            if (!seen_font) print "gtk-font-name=" font
            if (!seen_icons) print "gtk-icon-theme-name=" icons
            if (!seen_cursor) print "gtk-cursor-theme-name=" cursor
        }
        BEGIN { in_settings = 0; found_settings = 0 }
        /^\[Settings\][[:space:]]*$/ {
            if (in_settings) emit_missing()
            print
            in_settings = 1
            found_settings = 1
            next
        }
        /^\[/ {
            if (in_settings) {
                emit_missing()
                in_settings = 0
            }
            print
            next
        }
        in_settings {
            key = $0
            sub(/[[:space:]]*=.*$/, "", key)
            gsub(/[[:space:]]/, "", key)
            if (key == "gtk-theme-name") {
                print "gtk-theme-name=" theme
                seen_theme = 1
                next
            }
            if (key == "gtk-application-prefer-dark-theme") {
                if (dark != "omit")
                    print "gtk-application-prefer-dark-theme=" dark
                seen_dark = 1
                next
            }
            if (key == "gtk-font-name") {
                print "gtk-font-name=" font
                seen_font = 1
                next
            }
            if (key == "gtk-icon-theme-name") {
                print "gtk-icon-theme-name=" icons
                seen_icons = 1
                next
            }
            if (key == "gtk-cursor-theme-name") {
                print "gtk-cursor-theme-name=" cursor
                seen_cursor = 1
                next
            }
            print
            next
        }
        { print }
        END {
            if (in_settings) {
                emit_missing()
            } else if (!found_settings) {
                if (NR > 0) print ""
                print "[Settings]"
                emit_missing()
            }
        }
    ' "$source_file" >"$temporary"

    if [ -f "$ini_file" ]; then
        chmod --reference="$ini_file" "$temporary" 2>/dev/null || chmod 600 "$temporary"
    else
        chmod 600 "$temporary"
    fi
    mv -f "$temporary" "$ini_file"
}

set_gsetting() {
    schema=$1
    key=$2
    value=$3
    command -v gsettings >/dev/null 2>&1 || return 0
    gsettings writable "$schema" "$key" 2>/dev/null |
        grep -qx true || return 0
    gsettings set "$schema" "$key" "$value"
}

write_gtk4_css() {
    target=$1
    temporary=$(mktemp "$(dirname "$target")/.voidline-gtk4.XXXXXX")
    cat >"$temporary" <<EOF
/* Generated by Voidline. Edit the shell palette, not this cache. */
:root {
  --window-bg-color: $background;
  --window-fg-color: $text;
  --view-bg-color: $surface_low;
  --view-fg-color: $text;
  --headerbar-bg-color: $panel;
  --headerbar-fg-color: $text;
  --sidebar-bg-color: $group;
  --sidebar-fg-color: $text;
  --card-bg-color: $raised;
  --card-fg-color: $text;
  --popover-bg-color: $raised;
  --popover-fg-color: $text;
  --dialog-bg-color: $panel;
  --dialog-fg-color: $text;
  --accent-bg-color: $accent;
  --accent-fg-color: $accent_ink;
  --accent-color: $accent;
  --border-color: $outline;
  --voidline-accent-container: $accent_container;
  --voidline-muted-color: $muted;
}

@define-color window_bg_color $background;
@define-color window_fg_color $text;
@define-color view_bg_color $surface_low;
@define-color view_fg_color $text;
@define-color headerbar_bg_color $panel;
@define-color headerbar_fg_color $text;
@define-color sidebar_bg_color $group;
@define-color sidebar_fg_color $text;
@define-color card_bg_color $raised;
@define-color card_fg_color $text;
@define-color popover_bg_color $raised;
@define-color popover_fg_color $text;
@define-color accent_bg_color $accent;
@define-color accent_fg_color $accent_ink;
@define-color accent_color $accent;
@define-color borders $outline;

window.nautilus-window {
  background-color: var(--window-bg-color);
  color: var(--window-fg-color);
}

.nautilus-window headerbar,
.nautilus-window .toolbar {
  background-color: var(--headerbar-bg-color);
  color: var(--headerbar-fg-color);
  box-shadow: inset 0 -1px $outline;
}

.nautilus-window .navigation-sidebar,
.nautilus-window placessidebar,
.nautilus-window .sidebar-pane {
  background-color: var(--sidebar-bg-color);
  color: var(--sidebar-fg-color);
}

.nautilus-window .navigation-sidebar row,
.nautilus-window placessidebar row {
  min-height: 38px;
  margin: 2px 7px;
  border-radius: 14px;
}

.nautilus-window .navigation-sidebar row:hover,
.nautilus-window placessidebar row:hover {
  background-color: $raised;
}

.nautilus-window .navigation-sidebar row:selected,
.nautilus-window placessidebar row:selected {
  background-color: var(--voidline-accent-container);
  color: $accent;
}

.nautilus-window .view,
.nautilus-window gridview,
.nautilus-window columnview,
.nautilus-window listview {
  background-color: var(--view-bg-color);
  color: var(--view-fg-color);
}

.nautilus-window gridview child,
.nautilus-window listview row {
  border-radius: 14px;
}

.nautilus-window gridview child:selected,
.nautilus-window listview row:selected {
  background-color: var(--voidline-accent-container);
  color: var(--view-fg-color);
}

.nautilus-window button,
.nautilus-window entry,
.nautilus-window .path-bar button {
  border-radius: 14px;
}

.nautilus-window .path-bar button:checked,
.nautilus-window button:checked {
  background-color: var(--voidline-accent-container);
  color: $accent;
}

.nautilus-window popover contents,
.nautilus-window dialog,
.nautilus-window .card {
  background-color: var(--card-bg-color);
  color: var(--card-fg-color);
  border: 1px solid $outline;
  border-radius: 20px;
}

.nautilus-window .dim-label,
.nautilus-window .caption {
  color: var(--voidline-muted-color);
}
EOF
    chmod 600 "$temporary"
    mv -f "$temporary" "$target"
}

write_gtk3_css() {
    target=$1
    temporary=$(mktemp "$(dirname "$target")/.voidline-gtk3.XXXXXX")
    cat >"$temporary" <<EOF
/* Generated by Voidline. Edit the shell palette, not this cache. */
@define-color theme_bg_color $background;
@define-color theme_fg_color $text;
@define-color theme_base_color $surface_low;
@define-color theme_text_color $text;
@define-color theme_selected_bg_color $accent;
@define-color theme_selected_fg_color $accent_ink;
@define-color insensitive_bg_color $group;
@define-color insensitive_fg_color $muted;
@define-color borders $outline;

window,
dialog {
  background-color: @theme_bg_color;
  color: @theme_fg_color;
}

/*
 * GTK3 CSD shadows reserve transparent pixels inside the compositor's window
 * bounds. Hyprland then draws its border around those pixels, leaving a strip
 * of wallpaper between the application and border. Let Hyprland own the
 * shadow and border instead.
 */
decoration,
window.csd decoration,
window.background.csd decoration {
  margin: 0;
  padding: 0;
  border: none;
  border-radius: 16px;
  box-shadow: none;
}

window.csd,
window.background.csd {
  background-color: @theme_bg_color;
  color: @theme_fg_color;
  border-radius: 16px;
}

headerbar,
toolbar {
  background-image: none;
  background-color: $panel;
  color: @theme_fg_color;
  border-color: @borders;
  box-shadow: inset 0 -1px @borders;
}

button,
entry,
combobox button {
  background-image: none;
  background-color: $raised;
  color: @theme_fg_color;
  border: 1px solid @borders;
  border-radius: 12px;
  box-shadow: none;
}

button:hover,
entry:focus,
combobox button:hover {
  background-image: none;
  background-color: $accent_container;
  color: @theme_fg_color;
  border-color: $accent;
}

button:active,
button:checked,
button.suggested-action {
  background-image: none;
  background-color: $accent;
  color: $accent_ink;
  border-color: $accent;
}

button:disabled,
entry:disabled {
  background-image: none;
  background-color: $group;
  color: $muted;
  border-color: @borders;
}

treeview.view,
textview text,
iconview {
  background-color: @theme_base_color;
  color: @theme_text_color;
}

treeview.view:selected,
iconview:selected {
  background-image: none;
  background-color: $accent_container;
  color: @theme_text_color;
}

.sidebar,
placessidebar,
filechooser placessidebar {
  background-color: $group;
  color: @theme_fg_color;
}

.sidebar row,
placessidebar row,
filechooser placessidebar row {
  background-image: none;
  background-color: transparent;
  color: @theme_fg_color;
  min-height: 38px;
  margin: 2px 7px;
  border-radius: 12px;
}

.sidebar row:hover,
placessidebar row:hover,
filechooser placessidebar row:hover {
  background-image: none;
  background-color: $raised;
  color: @theme_fg_color;
}

.sidebar row:selected,
placessidebar row:selected,
filechooser placessidebar row:selected {
  background-image: none;
  background-color: $accent_container;
  color: @theme_fg_color;
}

filechooser {
  background-color: @theme_bg_color;
  color: @theme_fg_color;
}

filechooser paned,
filechooser stack,
filechooser scrolledwindow,
filechooser viewport {
  background-color: @theme_base_color;
  color: @theme_text_color;
}

filechooser treeview.view {
  background-color: @theme_base_color;
  color: @theme_text_color;
}

filechooser treeview.view header button {
  background-image: none;
  background-color: $raised;
  color: @theme_fg_color;
  border-color: @borders;
  border-radius: 8px;
}

filechooser treeview.view header button:hover {
  background-image: none;
  background-color: $accent_container;
  color: @theme_fg_color;
}

filechooser separator,
separator {
  background-color: @borders;
}

popover,
popover.background {
  background-image: none;
  background-color: $raised;
  color: @theme_fg_color;
  border: 1px solid @borders;
  border-radius: 16px;
}
EOF
    chmod 600 "$temporary"
    mv -f "$temporary" "$target"
}

write_voidline_icon_theme() {
    base_theme=$1
    [ "$base_theme" = Voidline ] && base_theme=Papirus-Dark

    theme_root=${XDG_DATA_HOME:-"$HOME/.local/share"}/icons/Voidline
    source_root=$theme_root/source/material-symbols
    if [ ! -f "$source_root/folder.svg" ] \
            && [ -f /usr/share/voidline/material-symbols/folder.svg ]; then
        source_root=/usr/share/voidline/material-symbols
    fi
    user_icons=${XDG_DATA_HOME:-"$HOME/.local/share"}/icons
    if [ ! -d "$user_icons/$base_theme" ] \
        && [ ! -d "/usr/share/icons/$base_theme" ]; then
        if [ -d /usr/share/icons/breeze-dark ]; then
            base_theme=breeze-dark
        else
            base_theme=Adwaita
        fi
    fi

    # The source files are the unmodified rounded Material Symbols SVGs from
    # Google's official material-design-icons repository. Never manufacture a
    # generic folder silhouette here: each standard Linux icon name maps to a
    # distinct upstream symbol and inherits only Voidline's current palette.
    [ -f "$source_root/folder.svg" ] || return 0

    places_directory=$theme_root/scalable/places
    mimetypes_directory=$theme_root/scalable/mimetypes
    devices_directory=$theme_root/scalable/devices
    apps_directory=$theme_root/scalable/apps
    mkdir -p "$places_directory" "$mimetypes_directory" \
        "$devices_directory" "$apps_directory"

    temporary=$(mktemp "$theme_root/.index.theme.XXXXXX")
    cat >"$temporary" <<EOF
[Icon Theme]
Name=Voidline
Comment=Wallpaper-aware official Material Symbols icon theme
Inherits=$base_theme,hicolor
Directories=scalable/places,scalable/mimetypes,scalable/devices,scalable/apps

[scalable/places]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=Places

[scalable/mimetypes]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=MimeTypes

[scalable/devices]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=Devices

[scalable/apps]
Size=64
MinSize=16
MaxSize=512
Type=Scalable
Context=Applications
EOF
    chmod 644 "$temporary"
    mv -f "$temporary" "$theme_root/index.theme"

    material_icon() {
        source_name=$1
        directory=$2
        target_name=$3
        icon_color=$4
        source_file=$source_root/$source_name.svg
        [ -f "$source_file" ] || return 0
        target=$directory/$target_name.svg
        temporary=$(mktemp "$directory/.material-icon.XXXXXX")
        sed "s|<path |<path fill=\"$icon_color\" |" "$source_file" >"$temporary"
        chmod 644 "$temporary"
        mv -f "$temporary" "$target"
    }

    # Places and user folders.
    material_icon folder "$places_directory" folder "$accent_container"
    material_icon folder_open "$places_directory" folder-open "$accent_container"
    material_icon home "$places_directory" user-home "$accent"
    material_icon desktop_windows "$places_directory" user-desktop "$secondary"
    material_icon description "$places_directory" folder-documents "$accent"
    material_icon download "$places_directory" folder-download "$secondary"
    material_icon music_note "$places_directory" folder-music "$tertiary"
    material_icon image "$places_directory" folder-pictures "$accent"
    material_icon movie "$places_directory" folder-videos "$secondary"
    material_icon public "$places_directory" folder-publicshare "$tertiary"
    material_icon draft "$places_directory" folder-templates "$accent"
    material_icon code "$places_directory" folder-projects "$secondary"
    material_icon delete "$places_directory" user-trash "$tertiary"
    material_icon delete "$places_directory" user-trash-full "$tertiary"
    material_icon language "$places_directory" network-workgroup "$secondary"
    material_icon cloud "$places_directory" folder-remote "$secondary"
    material_icon hard_drive "$places_directory" drive-harddisk "$accent"

    # MIME types use distinct upstream symbols rather than folder aliases.
    material_icon folder_zip "$mimetypes_directory" application-x-archive "$tertiary"
    material_icon archive "$mimetypes_directory" package-x-generic "$tertiary"
    material_icon image "$mimetypes_directory" image-x-generic "$accent"
    material_icon audio_file "$mimetypes_directory" audio-x-generic "$tertiary"
    material_icon video_file "$mimetypes_directory" video-x-generic "$secondary"
    material_icon article "$mimetypes_directory" text-x-generic "$text"
    material_icon description "$mimetypes_directory" x-office-document "$accent"
    material_icon picture_as_pdf "$mimetypes_directory" application-pdf "$tertiary"
    material_icon code "$mimetypes_directory" text-x-script "$secondary"
    material_icon settings "$mimetypes_directory" text-x-config "$muted"
    material_icon deployed_code "$mimetypes_directory" application-x-executable "$accent"
    material_icon unknown_document "$mimetypes_directory" unknown "$muted"
    material_icon unknown_document "$mimetypes_directory" application-octet-stream "$muted"

    # Drives and removable hardware.
    material_icon hard_drive "$devices_directory" drive-harddisk "$accent"
    material_icon storage "$devices_directory" drive-removable-media "$secondary"
    material_icon sd_card "$devices_directory" media-flash "$tertiary"
    material_icon usb "$devices_directory" drive-removable-media-usb "$secondary"
    material_icon devices "$devices_directory" computer "$accent"
    material_icon language "$devices_directory" network-server "$secondary"

    # Default application fallback for launchers and unthemed desktop entries.
    material_icon apps "$apps_directory" application-default-icon "$accent"
    material_icon apps "$apps_directory" application-x-executable "$accent"
    material_icon apps "$apps_directory" application-x-voidline "$accent"

    # Common aliases and symbolic variants. Symbolic SVGs use currentColor so
    # GTK and Qt can recolor them for dark/light surfaces.
    cp -f "$places_directory/folder.svg" "$places_directory/inode-directory.svg"
    cp -f "$places_directory/folder.svg" "$places_directory/folder-recent.svg"
    cp -f "$places_directory/folder-open.svg" "$places_directory/folder-visiting.svg"
    cp -f "$places_directory/folder-download.svg" "$places_directory/folder-downloads.svg"
    cp -f "$places_directory/folder-pictures.svg" "$places_directory/folder-image.svg"
    cp -f "$mimetypes_directory/application-x-archive.svg" \
        "$mimetypes_directory/application-zip.svg"

    for source_file in "$places_directory"/*.svg "$mimetypes_directory"/*.svg \
        "$devices_directory"/*.svg "$apps_directory"/*.svg; do
        symbolic=${source_file%.svg}-symbolic.svg
        sed -E 's/fill="#[0-9A-Fa-f]{6}"/fill="currentColor"/g' \
            "$source_file" >"$symbolic"
        chmod 644 "$symbolic"
    done

    cp -f "$source_root/LICENSE" "$theme_root/LICENSE" 2>/dev/null || true

    command -v gtk-update-icon-cache >/dev/null 2>&1 \
        && gtk-update-icon-cache -f -t "$theme_root" >/dev/null 2>&1 || true
}

apply_theme() {
    [ "$#" -eq 17 ] || exit 2
    mode=$1
    background=$2
    panel=$3
    surface_low=$4
    group=$5
    raised=$6
    text=$7
    muted=$8
    outline=$9
    shift 9
    accent=$1
    secondary=$2
    tertiary=$3
    accent_container=$4
    accent_ink=$5
    interface_font=$6
    icon_theme=$7
    cursor_theme=$8

    case "$mode" in dark|light) ;; *) exit 2 ;; esac
    for color in "$background" "$panel" "$surface_low" "$group" "$raised" \
        "$text" "$muted" "$outline" "$accent" "$secondary" "$tertiary" \
        "$accent_container" "$accent_ink"; do
        valid_color "$color" || exit 2
    done
    valid_name "$interface_font" || exit 2
    valid_name "$icon_theme" || exit 2
    valid_name "$cursor_theme" || exit 2

    if [ "$mode" = dark ]; then
        color_scheme=prefer-dark
        gtk_theme=Adwaita-dark
        dark_value=1
    else
        color_scheme=prefer-light
        gtk_theme=Adwaita
        dark_value=0
    fi

    gtk3_directory=${XDG_CONFIG_HOME:-"$HOME/.config"}/gtk-3.0
    gtk4_directory=${XDG_CONFIG_HOME:-"$HOME/.config"}/gtk-4.0
    mkdir -p "$gtk3_directory" "$gtk4_directory"
    write_voidline_icon_theme "$icon_theme"
    effective_icon_theme=Voidline

    write_gtk3_css "$gtk3_directory/voidline.css"
    write_gtk4_css "$gtk4_directory/voidline.css"
    ensure_import "$gtk3_directory/gtk.css"
    ensure_import "$gtk4_directory/gtk.css"
    update_settings_ini "$gtk3_directory/settings.ini" "$gtk_theme" \
        "$dark_value" "$interface_font" "$effective_icon_theme" "$cursor_theme"
    # GTK4/libadwaita follows the freedesktop color-scheme setting. The old
    # GtkSettings dark flag is GTK3 compatibility-only and makes libadwaita
    # emit a warning when present in GTK4's settings.ini.
    update_settings_ini "$gtk4_directory/settings.ini" Adwaita \
        omit "$interface_font" "$effective_icon_theme" "$cursor_theme"

    if [ "${VOIDLINE_THEME_SKIP_GSETTINGS:-0}" != 1 ]; then
        set_gsetting org.gnome.desktop.interface color-scheme "$color_scheme"
        set_gsetting org.gnome.desktop.interface gtk-theme "$gtk_theme"
        set_gsetting org.gnome.desktop.interface icon-theme "$effective_icon_theme"
        set_gsetting org.gnome.desktop.interface font-name "$interface_font 11"
        set_gsetting org.gnome.desktop.interface cursor-theme "$cursor_theme"
    fi
}

case "${1:-}" in
    apply)
        shift
        apply_theme "$@"
        ;;
    *)
        exit 2
        ;;
esac
