# Voidline 0.3.0dev Hyprland integration
# This file is owned by Voidline. Put personal bindings in your main config.

exec-once = systemctl --user start voidline-shell.service

bind = SUPER, SPACE, global, quickshell:toggleLauncher
bind = SUPER, I, global, quickshell:toggleSettings
bind = SUPER, TAB, global, quickshell:toggleOverview
bind = CTRL ALT, DELETE, global, quickshell:togglePowerMenu
bind = SUPER, PERIOD, global, quickshell:openClipboardSymbols
bind = SUPER, V, global, quickshell:openClipboardHistory
bind = SUPER, A, global, quickshell:openActionCenter
bind = SUPER, Q, global, quickshell:openFileSearch
bind = SUPER, L, global, quickshell:lockScreen
bind = , PRINT, exec, voidlinectl screenshot screen
bind = SUPER SHIFT, S, exec, voidlinectl screenshot region
bind = SUPER SHIFT, C, exec, voidlinectl color-picker
